export const translations = {
  en: {
    AccountSettings: 'Account Setting',
    SignIn: 'Sign In',
    SignUp: 'Sign Up',
    GoBack: 'Go Back',
    VisitFirst: 'Dont have an account? Create here!',
    Home: 'Home',
    Contacts: 'Contacts',
    Contact: 'Contact',
    Articles: 'Articles',
    Article: 'Article',
    Add: 'Add',
    AddNew: 'Add a new:',
    NoContacts: 'No Contacts Yet!',
    NoArticles: 'No Articles Yet!',
    Welcome: 'Welcome',
    HomeDescription: 'Here you can manage your contacts and other personal information',
    Create: 'Create a new Article/Contact',
    HomeDescriptionWithItems: 'Welcome! Add more personal infromation',
    Here: 'Here',
    OpenCamera: 'Open a Camera',
    SelectImages: 'Select Images',
    SelectLanguage: 'Select Language',
    UserName: 'User Name',
    Settings: 'Settings',
    Open: 'Open',
    Edit: 'Edit',
    Submit: 'Submit',
    Recent: 'Recent Articles/Contacts',
    Birthday: 'Birthday',
    WebSite: 'Web Site',
    PickDate: 'Pick a Date',
    AddLocation: 'Add the Location',
    Email: 'Email',
    Password: 'Password',
    Title: 'Title',
    Description: 'Description',
    Info: 'Info',
    FirstName: 'First Name',
    LastName: 'Last Name',
    InvalidEmail: 'Invalid Email',
    InvalidSite: 'Invalid Site',
    InvalidPhone: 'Phone number is not valid',
    Occupation: 'Occupation',
    PhoneNumber: 'Phone Number',
    Error: "Some Error Occurs! It'll be fix soon.Thanks!",
    ErrorOccurs: 'Some Error Occurs',
    ErrorNotification: 'Error!',
    Success: 'Success!',
    SettingsAction: 'Settings were changed!',
    AddNewArticleAction: 'Article was successfully created!',
    EditArticleAction: 'Article was changed!',
    RemoveArticleAction: 'Article was deleted!',
    AddNewContactAction: 'Contact was successfully created!',
    EditContactAction: 'Contact was changed!',
    RemoveContactAction: 'Contact was deleted!',
    ErrorAuthNotification: 'Wrong email or password!',
  },
  ru: {
    AccountSettings: 'Настройки Аккаунта',
    SignIn: 'Вход',
    SignUp: 'Регистрация',
    GoBack: 'Вернуться',
    VisitFirst: 'Не зарегистрированы? Вам сюда!',
    Home: 'Главная',
    Contacts: 'Контакты',
    Contact: 'Контакт',
    Articles: 'Заметки',
    Article: 'Заметку',
    Add: 'Создать',
    AddNew: 'Создать новый:',
    NoContacts: 'У Вас пока нет созданных контактов!',
    NoArticles: 'У Вас пока нет созданных заметок!',
    Welcome: 'Добро пожаловать',
    HomeDescription:
      'Здесь Вы можете управлять своими контактами, заметками и персональной информацией',
    Create: 'Создать новый Контакт/Заметку',
    HomeDescriptionWithItems: 'Добро пожаловать! Добавить больше личной информации',
    Here: 'Здесь',
    OpenCamera: 'Сделать фото',
    SelectImages: 'Выбрать из медиа',
    SelectLanguage: 'Выбрать язык',
    UserName: 'Имя Пользователя',
    Settings: 'Настройки',
    Open: 'Открыть',
    Edit: 'Редактировать',
    Submit: 'Отправить',
    Recent: 'Свежие Заметки/Контакты',
    Birthday: 'День Рождения',
    WebSite: 'Веб Сайт',
    FirstName: 'Имя',
    LastName: 'Фамилия',
    Occupation: 'Род деятельности',
    PhoneNumber: 'Телефон',
    PickDate: 'Выбрать Дату',
    AddLocation: 'Добавить Локацию',
    Email: 'Емейл',
    Password: 'Пароль',
    Title: 'Заголовок',
    Description: 'Описание',
    Required: 'Обязательно для заполнения',
    InvalidSite: 'Неправильный веб адрес',
    InvalidEmail: 'Неправильная почта',
    InvalidPhone: 'Некорректный телефон',
    Info: 'Информация',
    Error: 'Произошла ошибка!',
    ErrorOccurs: 'Произошла ошибка',
    ErrorNotification: 'Ошибка!',
    Success: 'Успех!',
    SettingsAction: 'Настройки успешно изменены!',
    AddNewArticleAction: 'Заметка успешно создана!',
    EditArticleAction: 'Заметка успешно изменена!',
    RemoveArticleAction: 'Заметка удалена!',
    AddNewContactAction: 'Контакт успешно создан!',
    EditContactAction: 'Контакт успешно изменен!',
    RemoveContactAction: 'Контакт удален!',
    ErrorAuthNotification: 'Неправильный email или пароль!',
  },
};
